language: java

dist: trusty

jdk: 
  - oraclejdk8

deploy:
  provider: script
  script:
    - ./gradlew test jacocoTestReport
    - bash find . -name jacocoTestReport.csv|xargs cat |awk -F',' '{print $3 " " $4" " $5}'    
    - ./gradlew clean jar
    - ./gradlew assemble
  on:
    branch:
      only:
        - ci-pipelines
    after_failure: echo "WIP"