language: java

dist: trusty

jdk: 
  - oraclejdk8

jobs:
  include:
    - stage: testing
      script: echo "testing coming soon"
    - stage: deploy
      branches:
        only:
        - ci-pipelines
      script:
        - ./gradlew clean jar
        - ./gradlew assemble