language: java

dist: trusty

jdk: 
  - oraclejdk8

jobs:
  include:
    - stage: test
      script: ./gradlew jacocoTestReport
    - stage: deploy
      branches:
        only:
          - ci-pipelines      
      provider: script
      script:
        - bash find . -name jacocoTestReport.csv|xargs cat |awk -F',' '{print $3 " " $4" " $5}'    
        - ./gradlew clean jar
        - ./gradlew assemble