language: java

dist: trusty

jdk: 
  - oraclejdk8

deploy:
  provider: script
  script:
    - COVERAGE = $COVERAGE ./gradlew -p ./monolithic/ui check
    - COVERAGE = $COVERAGE ./gradlew -p ./monolithic/service/cart check
    - COVERAGE = $COVERAGE ./gradlew -p ./monolithic/service/user check

    - COVERAGE = $COVERAGE ./gradlew -p ./monolithic/repository/order check
    - COVERAGE = $COVERAGE ./gradlew -p ./monolithic/repository/cart check
    - COVERAGE = $COVERAGE ./gradlew -p ./monolithic/repository/product check
    - COVERAGE = $COVERAGE ./gradlew -p ./monolithic/repository/user check
    
  on:
    branch:
      only:
        - ci-parallel-pipelines
    after_failure: echo "WIP"