language: java

dist: trusty

jdk: 
  - oraclejdk8

jobs:
  include:
    - stage: test
      script: echo "testing coming soon"
    - stage: deploy
      script:
        - ./gradlew clean jar
        - ./gradlew assemble