language: java
dist: trusty
matrix:
  include:
  # JDK Oracle JDK 8
  - jdk: oraclejdk8
    os: linux
  # JDK Oracle JDK 9
  - jdk: oraclejdk9
    os: linux

before_install:
- chmod +x gradlew
- wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

script: 
 - COVERAGE = $COVERAGE ./gradlew -p ./monolithic/ui check

 - COVERAGE = $COVERAGE ./gradlew -p ./monolithic/service/cart check
 - COVERAGE = $COVERAGE ./gradlew -p ./monolithic/service/user check

 - COVERAGE = $COVERAGE ./gradlew -p ./monolithic/repository/order check
 - COVERAGE = $COVERAGE ./gradlew -p ./monolithic/repository/cart check
 - COVERAGE = $COVERAGE ./gradlew -p ./monolithic/repository/product check
 - COVERAGE = $COVERAGE ./gradlew -p ./monolithic/repository/user check
 - bash -c "echo \"${DOCKER_PASSWORD}\" | docker login --username \"${DOCKER_LOGIN}\" --password-stdin"