language: java

dist: trusty

jdk: 
  - oraclejdk8

jobs:
  include:
    - stage: test
      script: ./gradlew test
    - stage: deploy
      branches:
        only:
        - ci-pipelines
      script:
        - ./gradlew clean jar
        - ./gradlew assemble