language: java

dist: trusty

jdk: 
  - oraclejdk8

jobs:
  include:
    - stage: test
      script: ./gradlew jacocoTestReport
      script: find . -name jacocoTestReport.csv|xargs cat |awk -F',' '{print $3 " " $4" " $5}'
    - stage: deploy
      branches:
        only:
        - ci-pipelines
      script:
        - ./gradlew clean jar
        - ./gradlew assemble